// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// clang-format off

#ifndef GTSTRUCT_0
#error  Define GTSTRUCT_0 before including this file.
#endif

#ifndef GTSTRUCT_N
#error  Define GTSTRUCT_N before including this file.
#endif

GTSTRUCT_0(UnOp        , GT_OP)
GTSTRUCT_0(Op          , GT_OP)

#ifndef FEATURE_EH_FUNCLETS
GTSTRUCT_N(EndLFin     , GT_END_LFIN)
#endif

GTSTRUCT_N(Jmp         , GT_JMP)

#ifdef TARGET_64BIT
GTSTRUCT_N(IntConCommon, GT_CNS_INT)
GTSTRUCT_N(IntCon      , GT_CNS_INT)
#else
GTSTRUCT_N(IntConCommon, GT_CNS_INT, GT_CNS_LNG)
GTSTRUCT_N(IntCon      , GT_CNS_INT)
GTSTRUCT_N(LngCon      , GT_CNS_LNG)
#endif

GTSTRUCT_N(DblCon      , GT_CNS_DBL)
GTSTRUCT_N(StrCon      , GT_CNS_STR)
GTSTRUCT_N(LclRef      , GT_LCL_LOAD, GT_LCL_STORE, GT_LCL_LOAD_FLD, GT_LCL_STORE_FLD, GT_LCL_ADDR)
GTSTRUCT_N(LclVar      , GT_LCL_LOAD, GT_LCL_STORE)
GTSTRUCT_N(LclLoad     , GT_LCL_LOAD)
GTSTRUCT_N(LclStore    , GT_LCL_STORE)
GTSTRUCT_N(LclFld      , GT_LCL_LOAD_FLD, GT_LCL_STORE_FLD)
GTSTRUCT_N(LclLoadFld  , GT_LCL_LOAD_FLD)
GTSTRUCT_N(LclStoreFld , GT_LCL_STORE_FLD)
GTSTRUCT_N(LclAddr     , GT_LCL_ADDR)
GTSTRUCT_N(LclDef      , GT_LCL_DEF)
GTSTRUCT_N(LclUse      , GT_LCL_USE)
GTSTRUCT_N(Phi         , GT_PHI)
GTSTRUCT_N(Insert      , GT_INSERT)
GTSTRUCT_N(Extract     , GT_EXTRACT)
GTSTRUCT_N(NullCheck   , GT_NULLCHECK)
GTSTRUCT_N(IndLoad     , GT_IND_LOAD)
GTSTRUCT_N(IndLoadBlk  , GT_IND_LOAD_BLK)
GTSTRUCT_N(IndLoadObj  , GT_IND_LOAD_OBJ)
GTSTRUCT_N(IndStore    , GT_IND_STORE)
GTSTRUCT_N(IndStoreBlk , GT_IND_STORE_BLK)
GTSTRUCT_N(IndStoreObj , GT_IND_STORE_OBJ)
GTSTRUCT_N(Blk         , GT_IND_LOAD_BLK, GT_IND_STORE_BLK, GT_IND_LOAD_OBJ, GT_IND_STORE_OBJ)
GTSTRUCT_N(Indir       , GT_IND_STORE, GT_IND_LOAD, GT_IND_LOAD_BLK, GT_IND_STORE_BLK, GT_IND_LOAD_OBJ, GT_IND_STORE_OBJ, GT_NULLCHECK)
GTSTRUCT_N(Box         , GT_BOX)
GTSTRUCT_N(FieldAddr   , GT_FIELD_ADDR)
GTSTRUCT_N(Call        , GT_CALL)
GTSTRUCT_N(FieldList   , GT_FIELD_LIST)
GTSTRUCT_N(MethodAddr  , GT_METHOD_ADDR)
GTSTRUCT_N(Intrinsic   , GT_INTRINSIC)
GTSTRUCT_N(IndexAddr   , GT_INDEX_ADDR)
GTSTRUCT_N(BoundsChk   , GT_BOUNDS_CHECK)
GTSTRUCT_N(ArrLen      , GT_ARR_LENGTH)
GTSTRUCT_N(ArrElem     , GT_ARR_ELEM)
GTSTRUCT_N(RetExpr     , GT_RET_EXPR)
GTSTRUCT_N(ILOffset    , GT_IL_OFFSET)
GTSTRUCT_N(CopyOrReload, GT_COPY, GT_RELOAD)
GTSTRUCT_N(ClsVar      , GT_CLS_VAR_ADDR)
GTSTRUCT_N(ConstAddr   , GT_CONST_ADDR)
GTSTRUCT_N(CmpXchg     , GT_CMPXCHG)
GTSTRUCT_N(AddrMode    , GT_LEA)
GTSTRUCT_N(DynBlk      , GT_COPY_BLK, GT_INIT_BLK)
GTSTRUCT_N(Qmark       , GT_QMARK)
GTSTRUCT_N(PutArgStk   , GT_PUTARG_STK)
GTSTRUCT_N(RegUse      , GT_REG_USE)

#ifdef FEATURE_HW_INTRINSICS
GTSTRUCT_N(HWIntrinsic , GT_HWINTRINSIC)
#endif

GTSTRUCT_N(AllocObj    , GT_ALLOCOBJ)
GTSTRUCT_N(RuntimeLookup, GT_RUNTIMELOOKUP)
GTSTRUCT_N(CC          , GT_JCC, GT_SETCC)
GTSTRUCT_N(Instr       , GT_INSTR)
GTSTRUCT_N(TernaryOp   , GT_CMPXCHG, GT_COPY_BLK, GT_INIT_BLK, GT_QMARK)

#undef  GTSTRUCT_0
#undef  GTSTRUCT_N
// clang-format on
