// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// x86 instructions for  the JIT compiler
//
// INST0-5 macro params:
//   id    - the enum name for the instruction
//   nm    - textual name (for assembly dipslay)
//   um    - update mode, see IUM_xx enum (rd, wr, or rw)
//   mr    - base encoding for R/M[reg] addressing mode
//   mi    - base encoding for R/M,icon addressing mode
//   rm    - base encoding for reg,R/M  addressing mode
//   a4    - base encoding for eax,i32  addressing mode
//   rr    - base encoding for register addressing mode
//   flags - flags, see INS_FLAGS_* enum
//
// The hex codes in this file represent the instruction encoding as follows:
//
//   0x0000ff00 - modrm byte position
//   0x000000ff - last byte of opcode (before modrm)
//   0x00ff0000 - first byte of opcode
//   0xff000000 - middle byte of opcode, if needed (after first, before last)
//
// Multi-byte opcodes without modrm are represented in mixed endian fashion.
//
// So a 1-byte opcode is:      and with modrm:
//             0x00000011          0x0000RM11
//
// So a 2-byte opcode is:      and with modrm:
//             0x00002211          0x0011RM22
//
// So a 3-byte opcode is:      and with modrm:
//             0x00113322          0x2211RM33
//
// So a 4-byte opcode would be something like this:
//             0x22114433

#define PACK3(byte1, byte2, byte3) (((byte1) << 16) | ((byte2) << 24) | (byte3))
#define PACK2(byte1, byte2) (((byte1) << 16) | (byte2))
#define PACK4(byte1, byte2, byte3, byte4) (((byte1) << 16) | ((byte2) << 24) | (byte3) | ((byte4) << 8))

#define PCKFLT(c) PACK2(0x0F, c)
#define SSEFLT(c) PACK3(0xF3, 0x0F, c)
#define SSEDBL(c) PACK3(0xF2, 0x0F, c)
#define PCKDBL(c) PACK3(0x66, 0x0F, c)
#define SSE38(c) PACK4(0x66, 0x0F, 0x38, c)
#define F20F38(c) PACK4(0xF2, 0x0F, 0x38, c)
#define SSE3A(c) PACK4(0x66, 0x0F, 0x3A, c)

// VEX* encodes the implied leading opcode bytes in c1:
// 1: implied 0f, 2: implied 0f 38, 3: implied 0f 3a
#define VEX2INT(c1, c2) PACK3(c1, 0xc5, c2)
#define VEX3INT(c1, c2) PACK4(c1, 0xc5, 0x02, c2)
#define VEX3FLT(c1, c2) PACK4(c1, 0xc5, 0x02, c2)

#ifdef TARGET_XARCH

// clang-format off
//    id                nm                  um      mr            mi            rm            a4            rr           flags
INST5(invalid,          "INVALID",          IUM_RD, BAD_CODE,     BAD_CODE,     BAD_CODE,     BAD_CODE,     BAD_CODE,    None)

INST5(push,             "push",             IUM_RD, 0x30FE,       0x68,         BAD_CODE,     BAD_CODE,     0x50,        None)
INST5(pop,              "pop",              IUM_WR, 0x008E,       BAD_CODE,     BAD_CODE,     BAD_CODE,     0x58,        None)
// Does not affect the stack tracking in the emitter
INST5(push_hide,        "push",             IUM_RD, 0x30FE,       0x68,         BAD_CODE,     BAD_CODE,     0x50,        None)
INST5(pop_hide,         "pop",              IUM_WR, 0x008E,       BAD_CODE,     BAD_CODE,     BAD_CODE,     0x58,        None)
#ifdef TARGET_X86
INST5(inc_s,            "inc",              IUM_RW, 0x00FE,       BAD_CODE,     BAD_CODE,     BAD_CODE,     0x40,        IncDecFlags)
INST5(dec_s,            "dec",              IUM_RW, 0x08FE,       BAD_CODE,     BAD_CODE,     BAD_CODE,     0x48,        IncDecFlags)
#endif
INST5(bswap,            "bswap",            IUM_RW, PCKFLT(0xC8), BAD_CODE,     BAD_CODE,     BAD_CODE,     0xC80F,      None)

//    id                nm                  um      mr            mi            rm            a4                         flags
INST4(add,              "add",              IUM_RW, 0x00,         0x0080,       0x02,         0x04,                      AddSubFlags)
INST4(or,               "or",               IUM_RW, 0x08,         0x0880,       0x0A,         0x0C,                      BitwiseFlags)
INST4(adc,              "adc",              IUM_RW, 0x10,         0x1080,       0x12,         0x14,                      AddSubCarryFlags)
INST4(sbb,              "sbb",              IUM_RW, 0x18,         0x1880,       0x1A,         0x1C,                      AddSubCarryFlags)
INST4(and,              "and",              IUM_RW, 0x20,         0x2080,       0x22,         0x24,                      BitwiseFlags)
INST4(sub,              "sub",              IUM_RW, 0x28,         0x2880,       0x2A,         0x2C,                      AddSubFlags)
INST4(xor,              "xor",              IUM_RW, 0x30,         0x3080,       0x32,         0x34,                      BitwiseFlags)
INST4(cmp,              "cmp",              IUM_RD, 0x38,         0x3880,       0x3A,         0x3C,                      AddSubFlags)
INST4(test,             "test",             IUM_RD, 0x84,         0x00F6,       0x84,         0xA8,                      BitwiseFlags)
INST4(mov,              "mov",              IUM_WR, 0x88,         0x00C6,       0x8A,         0xB0,                      None)

//    id                nm                  um      mr            mi            rm                                       flags
INST3(lea,              "lea",              IUM_WR, BAD_CODE,     BAD_CODE,     0x8D,                                    None)
INST3(bt,               "bt",               IUM_RD, PCKFLT(0xA3), BAD_CODE,     PCKFLT(0xA3),                            BitTestFlags)
INST3(bsf,              "bsf",              IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0xBC),                            BitScanFlags)
INST3(bsr,              "bsr",              IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0xBD),                            BitScanFlags)
INST3(movsx,            "movsx",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0xBE),                            None)
#ifdef TARGET_AMD64
INST3(movsxd,           "movsxd",           IUM_WR, BAD_CODE,     BAD_CODE,     0x63,                                    None)
#endif
INST3(movzx,            "movzx",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0xB6),                            None)

INST3(cmovo,            "cmovo",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x40),                            CcFlags_o)
INST3(cmovno,           "cmovno",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x41),                            CcFlags_no)
INST3(cmovb,            "cmovb",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x42),                            CcFlags_b)
INST3(cmovae,           "cmovae",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x43),                            CcFlags_ae)
INST3(cmove,            "cmove",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x44),                            CcFlags_e)
INST3(cmovne,           "cmovne",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x45),                            CcFlags_ne)
INST3(cmovbe,           "cmovbe",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x46),                            CcFlags_be)
INST3(cmova,            "cmova",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x47),                            CcFlags_a)
INST3(cmovs,            "cmovs",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x48),                            CcFlags_s)
INST3(cmovns,           "cmovns",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x49),                            CcFlags_ns)
INST3(cmovp,            "cmovp",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x4A),                            CcFlags_p)
INST3(cmovnp,           "cmovnp",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x4B),                            CcFlags_np)
INST3(cmovl,            "cmovl",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x4C),                            CcFlags_l)
INST3(cmovge,           "cmovge",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x4D),                            CcFlags_ge)
INST3(cmovle,           "cmovle",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x4E),                            CcFlags_le)
INST3(cmovg,            "cmovg",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x4F),                            CcFlags_g)

INST3(xchg,             "xchg",             IUM_RW, 0x86,         BAD_CODE,     0x86,                                    None)
INST3(imul,             "imul",             IUM_RW, BAD_CODE,     BAD_CODE,     PCKFLT(0xAF),                            ImulFlags)
INST3(imuli,            "imul",             IUM_RD, BAD_CODE,     BAD_CODE,     0x68,                                    ImulFlags)

//    id                nm                  um      mr            mi            rm                                       flags
INST3(FIRST_SSE_INSTRUCTION, "FIRST_SSE_INSTRUCTION", IUM_WR, BAD_CODE, BAD_CODE, BAD_CODE, None)
INST3(pmovmskb,         "pmovmskb",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xD7),                            None)
INST3(movmskpd,         "movmskpd",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x50),                            None)
INST3(movd,             "movd",             IUM_WR, PCKDBL(0x7E), BAD_CODE,     PCKDBL(0x6E),                            None) // Cleanup https://github.com/dotnet/runtime/issues/47943
INST3(movq,             "movq",             IUM_WR, PCKDBL(0xD6), BAD_CODE,     SSEFLT(0x7E),                            None) // Cleanup https://github.com/dotnet/runtime/issues/47943
INST3(movsdsse2,        "movsd",            IUM_WR, SSEDBL(0x11), BAD_CODE,     SSEDBL(0x10),                            AvxDstSrcSrc)
INST3(punpckldq,        "punpckldq",        IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x62),                            AvxDstDstSrc)
INST3(xorps,            "xorps",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x57),                            AvxDstDstSrc)
INST3(cvttsd2si,        "cvttsd2si",        IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x2C),                            None)
INST3(movntdq,          "movntdq",          IUM_WR, PCKDBL(0xE7), BAD_CODE,     BAD_CODE,                                None)
INST3(movnti,           "movnti",           IUM_WR, PCKFLT(0xC3), BAD_CODE,     BAD_CODE,                                None)
INST3(movntpd,          "movntpd",          IUM_WR, PCKDBL(0x2B), BAD_CODE,     BAD_CODE,                                None)
INST3(movntps,          "movntps",          IUM_WR, PCKFLT(0x2B), BAD_CODE,     BAD_CODE,                                None)
INST3(movdqu,           "movdqu",           IUM_WR, SSEFLT(0x7F), BAD_CODE,     SSEFLT(0x6F),                            None)
INST3(movdqa,           "movdqa",           IUM_WR, PCKDBL(0x7F), BAD_CODE,     PCKDBL(0x6F),                            None)
INST3(movlpd,           "movlpd",           IUM_WR, PCKDBL(0x13), BAD_CODE,     PCKDBL(0x12),                            AvxDstSrcSrc)
INST3(movlps,           "movlps",           IUM_WR, PCKFLT(0x13), BAD_CODE,     PCKFLT(0x12),                            AvxDstSrcSrc)
INST3(movhpd,           "movhpd",           IUM_WR, PCKDBL(0x17), BAD_CODE,     PCKDBL(0x16),                            AvxDstSrcSrc)
INST3(movhps,           "movhps",           IUM_WR, PCKFLT(0x17), BAD_CODE,     PCKFLT(0x16),                            AvxDstSrcSrc)
INST3(movss,            "movss",            IUM_WR, SSEFLT(0x11), BAD_CODE,     SSEFLT(0x10),                            AvxDstSrcSrc)
INST3(movapd,           "movapd",           IUM_WR, PCKDBL(0x29), BAD_CODE,     PCKDBL(0x28),                            None)
INST3(movaps,           "movaps",           IUM_WR, PCKFLT(0x29), BAD_CODE,     PCKFLT(0x28),                            None)
INST3(movupd,           "movupd",           IUM_WR, PCKDBL(0x11), BAD_CODE,     PCKDBL(0x10),                            None)
INST3(movups,           "movups",           IUM_WR, PCKFLT(0x11), BAD_CODE,     PCKFLT(0x10),                            None)
INST3(movhlps,          "movhlps",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x12),                            AvxDstDstSrc)
INST3(movlhps,          "movlhps",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x16),                            AvxDstDstSrc)
INST3(movmskps,         "movmskps",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x50),                            None)
INST3(unpckhps,         "unpckhps",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x15),                            AvxDstDstSrc)
INST3(unpcklps,         "unpcklps",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x14),                            AvxDstDstSrc)
INST3(maskmovdqu,       "maskmovdqu",       IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xF7),                            None)
INST3(shufps,           "shufps",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0xC6),                            AvxDstDstSrc)
INST3(shufpd,           "shufpd",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xC6),                            AvxDstDstSrc)
INST3(punpckhdq,        "punpckhdq",        IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x6A),                            AvxDstDstSrc)
INST3(lfence,           "lfence",           IUM_RD, 0x0FE8AE,     BAD_CODE,     BAD_CODE,                                None)
INST3(mfence,           "mfence",           IUM_RD, 0x0FF0AE,     BAD_CODE,     BAD_CODE,                                None)
INST3(prefetchnta,      "prefetchnta",      IUM_RD, 0x0F0018,     BAD_CODE,     BAD_CODE,                                None)
INST3(prefetcht0,       "prefetcht0",       IUM_RD, 0x0F0818,     BAD_CODE,     BAD_CODE,                                None)
INST3(prefetcht1,       "prefetcht1",       IUM_RD, 0x0F1018,     BAD_CODE,     BAD_CODE,                                None)
INST3(prefetcht2,       "prefetcht2",       IUM_RD, 0x0F1818,     BAD_CODE,     BAD_CODE,                                None)
INST3(sfence,           "sfence",           IUM_RD, 0x0FF8AE,     BAD_CODE,     BAD_CODE,                                None)
INST3(addps,            "addps",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x58),                            AvxDstDstSrc)
INST3(addss,            "addss",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x58),                            AvxDstDstSrc)
INST3(addpd,            "addpd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x58),                            AvxDstDstSrc)
INST3(addsd,            "addsd",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x58),                            AvxDstDstSrc)
INST3(mulps,            "mulps",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x59),                            AvxDstDstSrc)
INST3(mulss,            "mulss",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x59),                            AvxDstDstSrc)
INST3(mulpd,            "mulpd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x59),                            AvxDstDstSrc)
INST3(mulsd,            "mulsd",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x59),                            AvxDstDstSrc)
INST3(subps,            "subps",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x5C),                            AvxDstDstSrc)
INST3(subss,            "subss",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x5C),                            AvxDstDstSrc)
INST3(subpd,            "subpd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x5C),                            AvxDstDstSrc)
INST3(subsd,            "subsd",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x5C),                            AvxDstDstSrc)
INST3(minps,            "minps",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x5D),                            AvxDstDstSrc)
INST3(minss,            "minss",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x5D),                            AvxDstDstSrc)
INST3(minpd,            "minpd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x5D),                            AvxDstDstSrc)
INST3(minsd,            "minsd",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x5D),                            AvxDstDstSrc)
INST3(divps,            "divps",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x5E),                            AvxDstDstSrc)
INST3(divss,            "divss",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x5E),                            AvxDstDstSrc)
INST3(divpd,            "divpd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x5E),                            AvxDstDstSrc)
INST3(divsd,            "divsd",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x5E),                            AvxDstDstSrc)
INST3(maxps,            "maxps",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x5F),                            AvxDstDstSrc)
INST3(maxss,            "maxss",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x5F),                            AvxDstDstSrc)
INST3(maxpd,            "maxpd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x5F),                            AvxDstDstSrc)
INST3(maxsd,            "maxsd",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x5F),                            AvxDstDstSrc)
INST3(xorpd,            "xorpd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x57),                            AvxDstDstSrc)
INST3(andps,            "andps",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x54),                            AvxDstDstSrc)
INST3(andpd,            "andpd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x54),                            AvxDstDstSrc)
INST3(sqrtps,           "sqrtps",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x51),                            None)
INST3(sqrtss,           "sqrtss",           IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x51),                            AvxDstSrcSrc)
INST3(sqrtpd,           "sqrtpd",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x51),                            None)
INST3(sqrtsd,           "sqrtsd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x51),                            AvxDstSrcSrc)
INST3(andnps,           "andnps",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x55),                            AvxDstDstSrc)
INST3(andnpd,           "andnpd",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x55),                            AvxDstDstSrc)
INST3(orps,             "orps",             IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x56),                            AvxDstDstSrc)
INST3(orpd,             "orpd",             IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x56),                            AvxDstDstSrc)
INST3(haddpd,           "haddpd",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x7C),                            AvxDstDstSrc)
INST3(haddps,           "haddps",           IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x7C),                            AvxDstDstSrc)
INST3(hsubpd,           "hsubpd",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x7D),                            AvxDstDstSrc)
INST3(hsubps,           "hsubps",           IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x7D),                            AvxDstDstSrc)
INST3(addsubps,         "addsubps",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0xD0),                            AvxDstDstSrc)
INST3(addsubpd,         "addsubpd",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xD0),                            AvxDstDstSrc)
INST3(rcpps,            "rcpps",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x53),                            None)
INST3(rcpss,            "rcpss",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x53),                            AvxDstSrcSrc)
INST3(rsqrtps,          "rsqrtps",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x52),                            None)
INST3(rsqrtss,          "rsqrtss",          IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x52),                            AvxDstSrcSrc)
INST3(cvtpi2ps,         "cvtpi2ps",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x2A),                            None)
INST3(cvtsi2ss,         "cvtsi2ss",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x2A),                            AvxDstDstSrc)
INST3(cvtpi2pd,         "cvtpi2pd",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x2A),                            None)
INST3(cvtsi2sd,         "cvtsi2sd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x2A),                            AvxDstDstSrc)
INST3(cvttps2pi,        "cvttps2pi",        IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x2C),                            None)
INST3(cvttss2si,        "cvttss2si",        IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x2C),                            None)
INST3(cvttpd2pi,        "cvttpd2pi",        IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x2C),                            None)
INST3(cvtps2pi,         "cvtps2pi",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x2D),                            None)
INST3(cvtss2si,         "cvtss2si",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x2D),                            None)
INST3(cvtpd2pi,         "cvtpd2pi",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x2D),                            None)
INST3(cvtsd2si,         "cvtsd2si",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x2D),                            None)
INST3(cvtps2pd,         "cvtps2pd",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x5A),                            None)
INST3(cvtpd2ps,         "cvtpd2ps",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x5A),                            None)
INST3(cvtss2sd,         "cvtss2sd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x5A),                            AvxDstDstSrc)
INST3(cvtsd2ss,         "cvtsd2ss",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x5A),                            AvxDstDstSrc)
INST3(cvtdq2ps,         "cvtdq2ps",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0x5B),                            None)
INST3(cvtps2dq,         "cvtps2dq",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x5B),                            None)
INST3(cvttps2dq,        "cvttps2dq",        IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x5B),                            None)
INST3(cvtpd2dq,         "cvtpd2dq",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0xE6),                            None)
INST3(cvttpd2dq,        "cvttpd2dq",        IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xE6),                            None)
INST3(cvtdq2pd,         "cvtdq2pd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0xE6),                            None)
INST3(comiss,           "comiss",           IUM_RD, BAD_CODE,     BAD_CODE,     PCKFLT(0x2F),                            FComFlags)
INST3(comisd,           "comisd",           IUM_RD, BAD_CODE,     BAD_CODE,     PCKDBL(0x2F),                            FComFlags)
INST3(ucomiss,          "ucomiss",          IUM_RD, BAD_CODE,     BAD_CODE,     PCKFLT(0x2E),                            FComFlags)
INST3(ucomisd,          "ucomisd",          IUM_RD, BAD_CODE,     BAD_CODE,     PCKDBL(0x2E),                            FComFlags)
INST3(cmpps,            "cmpps",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKFLT(0xC2),                            AvxDstDstSrc)
INST3(cmppd,            "cmppd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xC2),                            AvxDstDstSrc)
INST3(cmpss,            "cmpss",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0xC2),                            AvxDstDstSrc)
INST3(cmpsd,            "cmpsd",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0xC2),                            AvxDstDstSrc)
INST3(paddb,            "paddb",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xFC),                            AvxDstDstSrc)
INST3(paddw,            "paddw",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xFD),                            AvxDstDstSrc)
INST3(paddd,            "paddd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xFE),                            AvxDstDstSrc)
INST3(paddq,            "paddq",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xD4),                            AvxDstDstSrc)
INST3(paddsb,           "paddsb",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xEC),                            AvxDstDstSrc)
INST3(paddsw,           "paddsw",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xED),                            AvxDstDstSrc)
INST3(paddusb,          "paddusb",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xDC),                            AvxDstDstSrc)
INST3(paddusw,          "paddusw",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xDD),                            AvxDstDstSrc)
INST3(pavgb,            "pavgb",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xE0),                            AvxDstDstSrc)
INST3(pavgw,            "pavgw",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xE3),                            AvxDstDstSrc)
INST3(psubb,            "psubb",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xF8),                            AvxDstDstSrc)
INST3(psubw,            "psubw",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xF9),                            AvxDstDstSrc)
INST3(psubd,            "psubd",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xFA),                            AvxDstDstSrc)
INST3(psubq,            "psubq",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xFB),                            AvxDstDstSrc)
INST3(pmaddwd,          "pmaddwd",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xF5),                            AvxDstDstSrc)
INST3(pmulhw,           "pmulhw",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xE5),                            AvxDstDstSrc)
INST3(pmulhuw,          "pmulhuw",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xE4),                            AvxDstDstSrc)
INST3(pmuludq,          "pmuludq",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xF4),                            AvxDstDstSrc)
INST3(pmullw,           "pmullw",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xD5),                            AvxDstDstSrc)
INST3(pand,             "pand",             IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xDB),                            AvxDstDstSrc)
INST3(pandn,            "pandn",            IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xDF),                            AvxDstDstSrc)
INST3(por,              "por",              IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xEB),                            AvxDstDstSrc)
INST3(pxor,             "pxor",             IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xEF),                            AvxDstDstSrc)
INST3(psadbw,           "psadbw",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xF6),                            AvxDstDstSrc)
INST3(psubsb,           "psubsb",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xE8),                            AvxDstDstSrc)
INST3(psubusb,          "psubusb",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xD8),                            AvxDstDstSrc)
INST3(psubsw,           "psubsw",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xE9),                            AvxDstDstSrc)
INST3(psubusw,          "psubusw",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xD9),                            AvxDstDstSrc)

// Note that the shift immediates share the same encoding between left and right-shift, and are distinguished by the Reg/Opcode,
// which is handled in emitxarch.cpp.
INST3(psrldq,           "psrldq",           IUM_WR, BAD_CODE,     PCKDBL(0x73), BAD_CODE,                                AvxDstDstSrc)
INST3(pslldq,           "pslldq",           IUM_WR, BAD_CODE,     PCKDBL(0x73), BAD_CODE,                                AvxDstDstSrc)
INST3(psllw,            "psllw",            IUM_WR, BAD_CODE,     PCKDBL(0x71), PCKDBL(0xF1),                            AvxDstDstSrc)
INST3(pslld,            "pslld",            IUM_WR, BAD_CODE,     PCKDBL(0x72), PCKDBL(0xF2),                            AvxDstDstSrc)
INST3(psllq,            "psllq",            IUM_WR, BAD_CODE,     PCKDBL(0x73), PCKDBL(0xF3),                            AvxDstDstSrc)
INST3(psrlw,            "psrlw",            IUM_WR, BAD_CODE,     PCKDBL(0x71), PCKDBL(0xD1),                            AvxDstDstSrc)
INST3(psrld,            "psrld",            IUM_WR, BAD_CODE,     PCKDBL(0x72), PCKDBL(0xD2),                            AvxDstDstSrc)
INST3(psrlq,            "psrlq",            IUM_WR, BAD_CODE,     PCKDBL(0x73), PCKDBL(0xD3),                            AvxDstDstSrc)
INST3(psraw,            "psraw",            IUM_WR, BAD_CODE,     PCKDBL(0x71), PCKDBL(0xE1),                            AvxDstDstSrc)
INST3(psrad,            "psrad",            IUM_WR, BAD_CODE,     PCKDBL(0x72), PCKDBL(0xE2),                            AvxDstDstSrc)

INST3(pmaxub,           "pmaxub",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xDE),                            AvxDstDstSrc)
INST3(pminub,           "pminub",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xDA),                            AvxDstDstSrc)
INST3(pmaxsw,           "pmaxsw",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xEE),                            AvxDstDstSrc)
INST3(pminsw,           "pminsw",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xEA),                            AvxDstDstSrc)
INST3(pcmpeqd,          "pcmpeqd",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x76),                            AvxDstDstSrc)
INST3(pcmpgtd,          "pcmpgtd",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x66),                            AvxDstDstSrc)
INST3(pcmpeqw,          "pcmpeqw",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x75),                            AvxDstDstSrc)
INST3(pcmpgtw,          "pcmpgtw",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x65),                            AvxDstDstSrc)
INST3(pcmpeqb,          "pcmpeqb",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x74),                            AvxDstDstSrc)
INST3(pcmpgtb,          "pcmpgtb",          IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x64),                            AvxDstDstSrc)
INST3(pshufd,           "pshufd",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x70),                            None)
INST3(pshufhw,          "pshufhw",          IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x70),                            None)
INST3(pshuflw,          "pshuflw",          IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x70),                            None)
INST3(pextrw,           "pextrw",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xC5),                            None)
INST3(pinsrw,           "pinsrw",           IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0xC4),                            AvxDstDstSrc)
INST3(punpckhbw,        "punpckhbw",        IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x68),                            AvxDstDstSrc)
INST3(punpcklbw,        "punpcklbw",        IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x60),                            AvxDstDstSrc)
INST3(punpckhqdq,       "punpckhqdq",       IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x6D),                            AvxDstDstSrc)
INST3(punpcklqdq,       "punpcklqdq",       IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x6C),                            AvxDstDstSrc)
INST3(punpckhwd,        "punpckhwd",        IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x69),                            AvxDstDstSrc)
INST3(punpcklwd,        "punpcklwd",        IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x61),                            AvxDstDstSrc)
INST3(unpckhpd,         "unpckhpd",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x15),                            AvxDstDstSrc)
INST3(unpcklpd,         "unpcklpd",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x14),                            AvxDstDstSrc)
INST3(packssdw,         "packssdw",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x6B),                            AvxDstDstSrc)
INST3(packsswb,         "packsswb",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x63),                            AvxDstDstSrc)
INST3(packuswb,         "packuswb",         IUM_WR, BAD_CODE,     BAD_CODE,     PCKDBL(0x67),                            AvxDstDstSrc)

//    id                nm                  um      mr            mi            rm                                       flags
INST3(dpps,             "dpps",             IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x40),                             AvxDstDstSrc)
INST3(dppd,             "dppd",             IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x41),                             AvxDstDstSrc)
INST3(insertps,         "insertps",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x21),                             AvxDstDstSrc)
INST3(pcmpeqq,          "pcmpeqq",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x29),                             AvxDstDstSrc)
INST3(pcmpgtq,          "pcmpgtq",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x37),                             AvxDstDstSrc)
INST3(pmulld,           "pmulld",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x40),                             AvxDstDstSrc)
INST3(ptest,            "ptest",            IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x17),                             None)
INST3(phaddd,           "phaddd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x02),                             AvxDstDstSrc)
INST3(pabsb,            "pabsb",            IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x1C),                             None)
INST3(pabsw,            "pabsw",            IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x1D),                             None)
INST3(pabsd,            "pabsd",            IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x1E),                             None)
INST3(palignr,          "palignr",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x0F),                             AvxDstDstSrc)
INST3(pmaddubsw,        "pmaddubsw",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x04),                             AvxDstDstSrc)
INST3(pmulhrsw,         "pmulhrsw",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x0B),                             AvxDstDstSrc)
INST3(pshufb,           "pshufb",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x00),                             AvxDstDstSrc)
INST3(psignb,           "psignb",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x08),                             AvxDstDstSrc)
INST3(psignw,           "psignw",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x09),                             AvxDstDstSrc)
INST3(psignd,           "psignd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x0A),                             AvxDstDstSrc)
INST3(pminsb,           "pminsb",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x38),                             AvxDstDstSrc)
INST3(pminsd,           "pminsd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x39),                             AvxDstDstSrc)
INST3(pminuw,           "pminuw",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x3A),                             AvxDstDstSrc)
INST3(pminud,           "pminud",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x3B),                             AvxDstDstSrc)
INST3(pmaxsb,           "pmaxsb",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x3C),                             AvxDstDstSrc)
INST3(pmaxsd,           "pmaxsd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x3D),                             AvxDstDstSrc)
INST3(pmaxuw,           "pmaxuw",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x3E),                             AvxDstDstSrc)
INST3(pmaxud,           "pmaxud",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x3F),                             AvxDstDstSrc)
INST3(pmovsxbw,         "pmovsxbw",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x20),                             None)
INST3(pmovsxbd,         "pmovsxbd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x21),                             None)
INST3(pmovsxbq,         "pmovsxbq",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x22),                             None)
INST3(pmovsxwd,         "pmovsxwd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x23),                             None)
INST3(pmovsxwq,         "pmovsxwq",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x24),                             None)
INST3(pmovsxdq,         "pmovsxdq",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x25),                             None)
INST3(pmovzxbw,         "pmovzxbw",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x30),                             None)
INST3(pmovzxbd,         "pmovzxbd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x31),                             None)
INST3(pmovzxbq,         "pmovzxbq",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x32),                             None)
INST3(pmovzxwd,         "pmovzxwd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x33),                             None)
INST3(pmovzxwq,         "pmovzxwq",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x34),                             None)
INST3(pmovzxdq,         "pmovzxdq",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x35),                             None)
INST3(packusdw,         "packusdw",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x2B),                             AvxDstDstSrc)
INST3(roundps,          "roundps",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x08),                             None)
INST3(roundss,          "roundss",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x0A),                             AvxDstSrcSrc)
INST3(roundpd,          "roundpd",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x09),                             None)
INST3(roundsd,          "roundsd",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x0B),                             AvxDstSrcSrc)
INST3(pmuldq,           "pmuldq",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x28),                             AvxDstDstSrc)
INST3(blendps,          "blendps",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x0C),                             AvxDstDstSrc)
INST3(blendvps,         "blendvps",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x14),                             None)
INST3(blendpd,          "blendpd",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x0D),                             AvxDstDstSrc)
INST3(blendvpd,         "blendvpd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x15),                             None)
INST3(pblendw,          "pblendw",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x0E),                             AvxDstDstSrc)
INST3(pblendvb,         "pblendvb",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x10),                             None)
INST3(phaddw,           "phaddw",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x01),                             AvxDstDstSrc)
INST3(phsubw,           "phsubw",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x05),                             AvxDstDstSrc)
INST3(phsubd,           "phsubd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x06),                             AvxDstDstSrc)
INST3(phaddsw,          "phaddsw",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x03),                             AvxDstDstSrc)
INST3(phsubsw,          "phsubsw",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x07),                             AvxDstDstSrc)
INST3(lddqu,            "lddqu",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0xF0),                            None)
INST3(movntdqa,         "movntdqa",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x2A),                             None)
INST3(movddup,          "movddup",          IUM_WR, BAD_CODE,     BAD_CODE,     SSEDBL(0x12),                            None)
INST3(movsldup,         "movsldup",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x12),                            None)
INST3(movshdup,         "movshdup",         IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0x16),                            None)
INST3(phminposuw,       "phminposuw",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x41),                             None)
INST3(mpsadbw,          "mpsadbw",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x42),                             AvxDstDstSrc)
INST3(pinsrb,           "pinsrb",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x20),                             AvxDstDstSrc)
INST3(pinsrd,           "pinsrd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x22),                             AvxDstDstSrc)
INST3(pinsrq,           "pinsrq",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x22),                             AvxDstDstSrc)
INST3(pextrb,           "pextrb",           IUM_WR, SSE3A(0x14),  BAD_CODE,     BAD_CODE,                                None)
INST3(pextrd,           "pextrd",           IUM_WR, SSE3A(0x16),  BAD_CODE,     BAD_CODE,                                None)
INST3(pextrq,           "pextrq",           IUM_WR, SSE3A(0x16),  BAD_CODE,     BAD_CODE,                                None)
INST3(pextrw_sse41,     "pextrw",           IUM_WR, SSE3A(0x15),  BAD_CODE,     BAD_CODE,                                None)
INST3(extractps,        "extractps",        IUM_WR, SSE3A(0x17),  BAD_CODE,     BAD_CODE,                                None)

INST3(pclmulqdq,        "pclmulqdq" ,       IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x44),                             AvxDstDstSrc)

INST3(aesdec,           "aesdec",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xDE),                             AvxDstDstSrc)
INST3(aesdeclast,       "aesdeclast",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xDF),                             AvxDstDstSrc)
INST3(aesenc,           "aesenc",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xDC),                             AvxDstDstSrc)
INST3(aesenclast,       "aesenclast",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xDD),                             AvxDstDstSrc)
INST3(aesimc,           "aesimc",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xDB),                             None)
INST3(aeskeygenassist,  "aeskeygenassist",  IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0xDF),                             None)
INST3(LAST_SSE_INSTRUCTION, "LAST_SSE_INSTRUCTION", IUM_WR, BAD_CODE, BAD_CODE, BAD_CODE, None)

INST3(FIRST_AVX_INSTRUCTION, "FIRST_AVX_INSTRUCTION", IUM_WR, BAD_CODE, BAD_CODE, BAD_CODE, None)
// AVX only instructions
INST3(vbroadcastss,     "broadcastss",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x18),                             None)
INST3(vbroadcastsd,     "broadcastsd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x19),                             None)
INST3(vpbroadcastb,     "pbroadcastb",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x78),                             None)
INST3(vpbroadcastw,     "pbroadcastw",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x79),                             None)
INST3(vpbroadcastd,     "pbroadcastd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x58),                             None)
INST3(vpbroadcastq,     "pbroadcastq",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x59),                             None)
INST3(vextractf128,     "extractf128",      IUM_WR, SSE3A(0x19),  BAD_CODE,     BAD_CODE,                                None)
INST3(vextracti128,     "extracti128",      IUM_WR, SSE3A(0x39),  BAD_CODE,     BAD_CODE,                                None)
INST3(vinsertf128,      "insertf128",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x18),                             AvxDstDstSrc)
INST3(vinserti128,      "inserti128",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x38),                             AvxDstDstSrc)
INST3(vzeroupper,       "zeroupper",        IUM_WR, 0xC577F8,     BAD_CODE,     BAD_CODE,                                None)
INST3(vperm2i128,       "perm2i128",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x46),                             AvxDstDstSrc)
INST3(vpermq,           "permq",            IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x00),                             None)
INST3(vpblendd,         "pblendd",          IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x02),                             AvxDstDstSrc)
INST3(vblendvps,        "blendvps",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x4A),                             AvxDstDstSrc)
INST3(vblendvpd,        "blendvpd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x4B),                             AvxDstDstSrc)
INST3(vpblendvb,        "pblendvb",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x4C),                             AvxDstDstSrc)
INST3(vtestps,          "testps",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x0E),                             None)
INST3(vtestpd,          "testpd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x0F),                             None)
INST3(vpsrlvd,          "psrlvd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x45),                             AvxDstDstSrc)
INST3(vpsrlvq,          "psrlvq",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x45),                             AvxDstDstSrc)
INST3(vpsravd,          "psravd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x46),                             AvxDstDstSrc)
INST3(vpsllvd,          "psllvd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x47),                             AvxDstDstSrc)
INST3(vpsllvq,          "psllvq",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x47),                             AvxDstDstSrc)
INST3(vpermilps,        "permilps",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x04),                             None)
INST3(vpermilpd,        "permilpd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x05),                             None)
INST3(vpermilpsvar,     "permilpsvar",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x0C),                             AvxDstDstSrc)
INST3(vpermilpdvar,     "permilpdvar",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x0D),                             AvxDstDstSrc)
INST3(vperm2f128,       "perm2f128",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x06),                             AvxDstDstSrc)
INST3(vpermpd,          "permpd",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0x01),                             None)
INST3(vpermd,           "permd",            IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x36),                             AvxDstDstSrc)
INST3(vpermps,          "permps",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x16),                             AvxDstDstSrc)
INST3(vbroadcastf128,   "broadcastf128",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x1A),                             None)
INST3(vbroadcasti128,   "broadcasti128",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x5A),                             None)
INST3(vmaskmovps,       "maskmovps",        IUM_WR, SSE38(0x2E),  BAD_CODE,     SSE38(0x2C),                             AvxDstDstSrc)
INST3(vmaskmovpd,       "maskmovpd",        IUM_WR, SSE38(0x2F),  BAD_CODE,     SSE38(0x2D),                             AvxDstDstSrc)
INST3(vpmaskmovd,       "pmaskmovd",        IUM_WR, SSE38(0x8E),  BAD_CODE,     SSE38(0x8C),                             AvxDstDstSrc)
INST3(vpmaskmovq,       "pmaskmovq",        IUM_WR, SSE38(0x8E),  BAD_CODE,     SSE38(0x8C),                             AvxDstDstSrc)
INST3(vpgatherdd,       "pgatherdd",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x90),                             AvxDstDstSrc)
INST3(vpgatherqd,       "pgatherqd",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x91),                             AvxDstDstSrc)
INST3(vpgatherdq,       "pgatherdq",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x90),                             AvxDstDstSrc)
INST3(vpgatherqq,       "pgatherqq",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x91),                             AvxDstDstSrc)
INST3(vgatherdps,       "gatherdps",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x92),                             AvxDstDstSrc)
INST3(vgatherqps,       "gatherqps",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x93),                             AvxDstDstSrc)
INST3(vgatherdpd,       "gatherdpd",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x92),                             AvxDstDstSrc)
INST3(vgatherqpd,       "gatherqpd",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x93),                             AvxDstDstSrc)

INST3(FIRST_FMA_INSTRUCTION, "FIRST_FMA_INSTRUCTION", IUM_WR, BAD_CODE, BAD_CODE, BAD_CODE, None)
//    id                nm                  um      mr            mi            rm                                       flags
INST3(vfmadd132pd,      "fmadd132pd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x98),                             AvxDstDstSrc)
INST3(vfmadd213pd,      "fmadd213pd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xA8),                             AvxDstDstSrc)
INST3(vfmadd231pd,      "fmadd231pd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xB8),                             AvxDstDstSrc)
INST3(vfmadd132ps,      "fmadd132ps",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x98),                             AvxDstDstSrc)
INST3(vfmadd213ps,      "fmadd213ps",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xA8),                             AvxDstDstSrc)
INST3(vfmadd231ps,      "fmadd231ps",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xB8),                             AvxDstDstSrc)
INST3(vfmadd132sd,      "fmadd132sd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x99),                             AvxDstDstSrc)
INST3(vfmadd213sd,      "fmadd213sd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xA9),                             AvxDstDstSrc)
INST3(vfmadd231sd,      "fmadd231sd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xB9),                             AvxDstDstSrc)
INST3(vfmadd132ss,      "fmadd132ss",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x99),                             AvxDstDstSrc)
INST3(vfmadd213ss,      "fmadd213ss",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xA9),                             AvxDstDstSrc)
INST3(vfmadd231ss,      "fmadd231ss",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xB9),                             AvxDstDstSrc)
INST3(vfmaddsub132pd,   "fmaddsub132pd",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x96),                             AvxDstDstSrc)
INST3(vfmaddsub213pd,   "fmaddsub213pd",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xA6),                             AvxDstDstSrc)
INST3(vfmaddsub231pd,   "fmaddsub231pd",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xB6),                             AvxDstDstSrc)
INST3(vfmaddsub132ps,   "fmaddsub132ps",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x96),                             AvxDstDstSrc)
INST3(vfmaddsub213ps,   "fmaddsub213ps",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xA6),                             AvxDstDstSrc)
INST3(vfmaddsub231ps,   "fmaddsub231ps",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xB6),                             AvxDstDstSrc)
INST3(vfmsubadd132pd,   "fmsubadd132pd",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x97),                             AvxDstDstSrc)
INST3(vfmsubadd213pd,   "fmsubadd213pd",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xA7),                             AvxDstDstSrc)
INST3(vfmsubadd231pd,   "fmsubadd231pd",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xB7),                             AvxDstDstSrc)
INST3(vfmsubadd132ps,   "fmsubadd132ps",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x97),                             AvxDstDstSrc)
INST3(vfmsubadd213ps,   "fmsubadd213ps",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xA7),                             AvxDstDstSrc)
INST3(vfmsubadd231ps,   "fmsubadd231ps",    IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xB7),                             AvxDstDstSrc)
INST3(vfmsub132pd,      "fmsub132pd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9A),                             AvxDstDstSrc)
INST3(vfmsub213pd,      "fmsub213pd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAA),                             AvxDstDstSrc)
INST3(vfmsub231pd,      "fmsub231pd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBA),                             AvxDstDstSrc)
INST3(vfmsub132ps,      "fmsub132ps",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9A),                             AvxDstDstSrc)
INST3(vfmsub213ps,      "fmsub213ps",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAA),                             AvxDstDstSrc)
INST3(vfmsub231ps,      "fmsub231ps",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBA),                             AvxDstDstSrc)
INST3(vfmsub132sd,      "fmsub132sd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9B),                             AvxDstDstSrc)
INST3(vfmsub213sd,      "fmsub213sd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAB),                             AvxDstDstSrc)
INST3(vfmsub231sd,      "fmsub231sd",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBB),                             AvxDstDstSrc)
INST3(vfmsub132ss,      "fmsub132ss",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9B),                             AvxDstDstSrc)
INST3(vfmsub213ss,      "fmsub213ss",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAB),                             AvxDstDstSrc)
INST3(vfmsub231ss,      "fmsub231ss",       IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBB),                             AvxDstDstSrc)
INST3(vfnmadd132pd,     "fnmadd132pd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9C),                             AvxDstDstSrc)
INST3(vfnmadd213pd,     "fnmadd213pd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAC),                             AvxDstDstSrc)
INST3(vfnmadd231pd,     "fnmadd231pd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBC),                             AvxDstDstSrc)
INST3(vfnmadd132ps,     "fnmadd132ps",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9C),                             AvxDstDstSrc)
INST3(vfnmadd213ps,     "fnmadd213ps",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAC),                             AvxDstDstSrc)
INST3(vfnmadd231ps,     "fnmadd231ps",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBC),                             AvxDstDstSrc)
INST3(vfnmadd132sd,     "fnmadd132sd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9D),                             AvxDstDstSrc)
INST3(vfnmadd213sd,     "fnmadd213sd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAD),                             AvxDstDstSrc)
INST3(vfnmadd231sd,     "fnmadd231sd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBD),                             AvxDstDstSrc)
INST3(vfnmadd132ss,     "fnmadd132ss",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9D),                             AvxDstDstSrc)
INST3(vfnmadd213ss,     "fnmadd213ss",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAD),                             AvxDstDstSrc)
INST3(vfnmadd231ss,     "fnmadd231ss",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBD),                             AvxDstDstSrc)
INST3(vfnmsub132pd,     "fnmsub132pd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9E),                             AvxDstDstSrc)
INST3(vfnmsub213pd,     "fnmsub213pd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAE),                             AvxDstDstSrc)
INST3(vfnmsub231pd,     "fnmsub231pd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBE),                             AvxDstDstSrc)
INST3(vfnmsub132ps,     "fnmsub132ps",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9E),                             AvxDstDstSrc)
INST3(vfnmsub213ps,     "fnmsub213ps",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAE),                             AvxDstDstSrc)
INST3(vfnmsub231ps,     "fnmsub231ps",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBE),                             AvxDstDstSrc)
INST3(vfnmsub132sd,     "fnmsub132sd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9F),                             AvxDstDstSrc)
INST3(vfnmsub213sd,     "fnmsub213sd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAF),                             AvxDstDstSrc)
INST3(vfnmsub231sd,     "fnmsub231sd",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBF),                             AvxDstDstSrc)
INST3(vfnmsub132ss,     "fnmsub132ss",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x9F),                             AvxDstDstSrc)
INST3(vfnmsub213ss,     "fnmsub213ss",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xAF),                             AvxDstDstSrc)
INST3(vfnmsub231ss,     "fnmsub231ss",      IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xBF),                             AvxDstDstSrc)
INST3(LAST_FMA_INSTRUCTION, "LAST_FMA_INSTRUCTION", IUM_WR, BAD_CODE, BAD_CODE, BAD_CODE, None)

INST3(FIRST_AVXVNNI_INSTRUCTION, "FIRST_AVXVNNI_INSTRUCTION", IUM_WR, BAD_CODE, BAD_CODE, BAD_CODE, None)
INST3(vpdpbusd,          "pdpbusd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x50),                             AvxDstDstSrc)
INST3(vpdpwssd,          "pdpwssd",         IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x52),                             AvxDstDstSrc)
INST3(vpdpbusds,         "pdpbusds",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x51),                             AvxDstDstSrc)
INST3(vpdpwssds,         "pdpwssds",        IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0x53),                             AvxDstDstSrc)
INST3(LAST_AVXVNNI_INSTRUCTION, "LAST_AVXVNNI_INSTRUCTION", IUM_WR, BAD_CODE, BAD_CODE, BAD_CODE, None)

INST3(FIRST_BMI_INSTRUCTION, "FIRST_BMI_INSTRUCTION", IUM_WR, BAD_CODE, BAD_CODE, BAD_CODE, None)
// BMI1
INST3(andn,             "andn",             IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xF2),                             AvxDstDstSrc)
INST3(blsi,             "blsi",             IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xF3),                             AvxDstDstSrc)
INST3(blsmsk,           "blsmsk",           IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xF3),                             AvxDstDstSrc)
INST3(blsr,             "blsr",             IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xF3),                             AvxDstDstSrc)
INST3(bextr,            "bextr",            IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xF7),                             AvxDstDstSrc)
// BMI2
INST3(rorx,             "rorx",             IUM_WR, BAD_CODE,     BAD_CODE,     SSE3A(0xF0),                             None)
INST3(pdep,             "pdep",             IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xF5),                             AvxDstDstSrc)
INST3(pext,             "pext",             IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xF5),                             AvxDstDstSrc)
INST3(bzhi,             "bzhi",             IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xF5),                             BzhiFlags | AvxDstDstSrc)
INST3(mulx,             "mulx",             IUM_WR, BAD_CODE,     BAD_CODE,     SSE38(0xF6),                             AvxDstDstSrc)
INST3(LAST_BMI_INSTRUCTION, "LAST_BMI_INSTRUCTION", IUM_WR, BAD_CODE, BAD_CODE, BAD_CODE, None)

INST3(LAST_AVX_INSTRUCTION, "LAST_AVX_INSTRUCTION", IUM_WR, BAD_CODE, BAD_CODE, BAD_CODE, None)
INST3(crc32,            "crc32",            IUM_WR, BAD_CODE,     BAD_CODE,     F20F38(0xF0),                            None)
INST3(tzcnt,            "tzcnt",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0xBC),                            ZCntFlags)
INST3(lzcnt,            "lzcnt",            IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0xBD),                            ZCntFlags)
INST3(popcnt,           "popcnt",           IUM_WR, BAD_CODE,     BAD_CODE,     SSEFLT(0xB8),                            PopCntFlags)

//    id                nm                  um      mr            mi                                                     flags
INST2(ret,              "ret",              IUM_RD, 0xC3,         0xC2,                                                  None)
INST2(call,             "call",             IUM_RD, 0x10FF,       0xE8,                                                  None)

INST2(rol,              "rol",              IUM_RW, 0x00D2,       BAD_CODE,                                              RotateNFlags)
INST2(rol_1,            "rol",              IUM_RW, 0x00D0,       0x00D0,                                                Rotate1Flags)
INST2(rol_N,            "rol",              IUM_RW, BAD_CODE,     0x00C0,                                                RotateNFlags)
INST2(ror,              "ror",              IUM_RW, 0x08D2,       BAD_CODE,                                              RotateNFlags)
INST2(ror_1,            "ror",              IUM_RW, 0x08D0,       0x08D0,                                                Rotate1Flags)
INST2(ror_N,            "ror",              IUM_RW, BAD_CODE,     0x08C0,                                                RotateNFlags)
INST2(rcl,              "rcl",              IUM_RW, 0x10D2,       BAD_CODE,                                              RotateCarryNFlags)
INST2(rcl_1,            "rcl",              IUM_RW, 0x10D0,       0x10D0,                                                RotateCarry1Flags)
INST2(rcl_N,            "rcl",              IUM_RW, BAD_CODE,     0x10C0,                                                RotateCarryNFlags) 
INST2(rcr,              "rcr",              IUM_RW, 0x18D2,       BAD_CODE,                                              RotateCarryNFlags)
INST2(rcr_1,            "rcr",              IUM_RW, 0x18D0,       0x18D0,                                                RotateCarry1Flags)   
INST2(rcr_N,            "rcr",              IUM_RW, BAD_CODE,     0x18C0,                                                RotateCarryNFlags)

INST2(shl,              "shl",              IUM_RW, 0x20D2,       BAD_CODE,                                              ShiftNFlags)
INST2(shl_1,            "shl",              IUM_RW, 0x20D0,       0x20D0,                                                Shift1Flags)
INST2(shl_N,            "shl",              IUM_RW, BAD_CODE,     0x20C0,                                                ShiftNFlags)
INST2(shr,              "shr",              IUM_RW, 0x28D2,       BAD_CODE,                                              ShiftNFlags)
INST2(shr_1,            "shr",              IUM_RW, 0x28D0,       0x28D0,                                                Shift1Flags)
INST2(shr_N,            "shr",              IUM_RW, BAD_CODE,     0x28C0,                                                ShiftNFlags)
INST2(sar,              "sar",              IUM_RW, 0x38D2,       BAD_CODE,                                              ShiftNFlags)
INST2(sar_1,            "sar",              IUM_RW, 0x38D0,       0x38D0,                                                Shift1Flags)
INST2(sar_N,            "sar",              IUM_RW, BAD_CODE,     0x38C0,                                                ShiftNFlags)

//    id                nm                  um      mr                                                                   flags
INST1(r_movsb,          "rep movsb",        IUM_RD, 0xA4F3,                                                              DirFlags)
INST1(r_movsd,          "rep movsd",        IUM_RD, 0xA5F3,                                                              DirFlags)
#ifdef TARGET_AMD64
INST1(r_movsq,          "rep movsq",        IUM_RD, 0xF3A548,                                                            DirFlags)
#endif
INST1(movsb,            "movsb",            IUM_RD, 0xA4,                                                                DirFlags)
INST1(movsd,            "movsd",            IUM_RD, 0xA5,                                                                DirFlags)
#ifdef TARGET_AMD64
INST1(movsq,            "movsq",            IUM_RD, 0xA548,                                                              DirFlags)
#endif
INST1(r_stosb,          "rep stosb",        IUM_RD, 0xAAF3,                                                              DirFlags)
INST1(r_stosd,          "rep stosd",        IUM_RD, 0xABF3,                                                              DirFlags)
#ifdef TARGET_AMD64
INST1(r_stosq,          "rep stosq",        IUM_RD, 0xF3AB48,                                                            DirFlags)
#endif
INST1(stosb,            "stosb",            IUM_RD, 0xAA,                                                                DirFlags)
INST1(stosd,            "stosd",            IUM_RD, 0xAB,                                                                DirFlags)
#ifdef TARGET_AMD64
INST1(stosq,            "stosq",            IUM_RD, 0xAB48,                                                              DirFlags)
#endif

INST1(int3,             "int3",             IUM_RD, 0xCC,                                                                None)
INST1(nop,              "nop",              IUM_RD, 0x90,                                                                None)
INST1(lock,             "lock",             IUM_RD, 0xF0,                                                                None)
INST1(leave,            "leave",            IUM_RD, 0xC9,                                                                None)

INST1(inc,              "inc",              IUM_RW, 0x00FE,                                                              IncDecFlags)
INST1(dec,              "dec",              IUM_RW, 0x08FE,                                                              IncDecFlags)

INST1(neg,              "neg",              IUM_RW, 0x18F6,                                                              AddSubFlags)
INST1(not,              "not",              IUM_RW, 0x10F6,                                                              None)

INST1(cdq,              "cdq",              IUM_RD, 0x99,                                                                None)
INST1(idiv,             "idiv",             IUM_RD, 0x38F6,                                                              DivFlags)
INST1(imulEAX,          "imul",             IUM_RD, 0x28F6,                                                              ImulFlags)
INST1(div,              "div",              IUM_RD, 0x30F6,                                                              DivFlags)
INST1(mulEAX,           "mul",              IUM_RD, 0x20F6,                                                              ImulFlags)

INST1(xadd,             "xadd",             IUM_RW, PCKFLT(0xC0),                                                        AddSubFlags)
INST1(cmpxchg,          "cmpxchg",          IUM_RW, PCKFLT(0xB0),                                                        AddSubFlags)

INST1(shld,             "shld",             IUM_RW, PCKFLT(0xA4),                                                        ShiftNFlags)
INST1(shrd,             "shrd",             IUM_RW, PCKFLT(0xAC),                                                        ShiftNFlags)

// For RyuJIT/x86, we follow the x86 calling convention that requires
// us to return floating point value on the x87 FP stack, so we need
// these instructions regardless of whether we're using full stack fp.
#ifdef TARGET_X86
INST1(fld,              "fld",              IUM_WR, 0x00D9,                                                              None)
INST1(fstp,             "fstp",             IUM_WR, 0x18D9,                                                              None)
#endif

INST1(seto,             "seto",             IUM_WR, PCKFLT(0x90),                                                        CcFlags_o)
INST1(setno,            "setno",            IUM_WR, PCKFLT(0x91),                                                        CcFlags_no)
INST1(setb,             "setb",             IUM_WR, PCKFLT(0x92),                                                        CcFlags_b)
INST1(setae,            "setae",            IUM_WR, PCKFLT(0x93),                                                        CcFlags_ae)
INST1(sete,             "sete",             IUM_WR, PCKFLT(0x94),                                                        CcFlags_e)
INST1(setne,            "setne",            IUM_WR, PCKFLT(0x95),                                                        CcFlags_ne)
INST1(setbe,            "setbe",            IUM_WR, PCKFLT(0x96),                                                        CcFlags_be)
INST1(seta,             "seta",             IUM_WR, PCKFLT(0x97),                                                        CcFlags_a)
INST1(sets,             "sets",             IUM_WR, PCKFLT(0x98),                                                        CcFlags_s)
INST1(setns,            "setns",            IUM_WR, PCKFLT(0x99),                                                        CcFlags_ns)
INST1(setp,             "setp",             IUM_WR, PCKFLT(0x9A),                                                        CcFlags_p)
INST1(setnp,            "setnp",            IUM_WR, PCKFLT(0x9B),                                                        CcFlags_np)
INST1(setl,             "setl",             IUM_WR, PCKFLT(0x9C),                                                        CcFlags_l)
INST1(setge,            "setge",            IUM_WR, PCKFLT(0x9D),                                                        CcFlags_ge)
INST1(setle,            "setle",            IUM_WR, PCKFLT(0x9E),                                                        CcFlags_le)
INST1(setg,             "setg",             IUM_WR, PCKFLT(0x9F),                                                        CcFlags_g)

#ifdef TARGET_AMD64
// A jump with rex prefix. This is used for register indirect tail calls.
INST1(rex_jmp,          "rex.jmp",          IUM_RD, 0x20FE,                                                              None)
#endif

INST1(i_jmp,            "jmp",              IUM_RD, 0x20FE,                                                              None)

INST0(jmp,              "jmp",              IUM_RD, 0xEB,                                                                None)
INST0(jo,               "jo",               IUM_RD, 0x70,                                                                CcFlags_o)
INST0(jno,              "jno",              IUM_RD, 0x71,                                                                CcFlags_no)
INST0(jb,               "jb",               IUM_RD, 0x72,                                                                CcFlags_b)
INST0(jae,              "jae",              IUM_RD, 0x73,                                                                CcFlags_ae)
INST0(je,               "je",               IUM_RD, 0x74,                                                                CcFlags_e)
INST0(jne,              "jne",              IUM_RD, 0x75,                                                                CcFlags_ne)
INST0(jbe,              "jbe",              IUM_RD, 0x76,                                                                CcFlags_be)
INST0(ja,               "ja",               IUM_RD, 0x77,                                                                CcFlags_a)
INST0(js,               "js",               IUM_RD, 0x78,                                                                CcFlags_s)
INST0(jns,              "jns",              IUM_RD, 0x79,                                                                CcFlags_ns)
INST0(jp,               "jp",               IUM_RD, 0x7A,                                                                CcFlags_p)
INST0(jnp,              "jnp",              IUM_RD, 0x7B,                                                                CcFlags_np)
INST0(jl,               "jl",               IUM_RD, 0x7C,                                                                CcFlags_l)
INST0(jge,              "jge",              IUM_RD, 0x7D,                                                                CcFlags_ge)
INST0(jle,              "jle",              IUM_RD, 0x7E,                                                                CcFlags_le)
INST0(jg,               "jg",               IUM_RD, 0x7F,                                                                CcFlags_g)

INST0(l_jmp,            "jmp",              IUM_RD, 0xE9,                                                                None)
INST0(l_jo,             "jo",               IUM_RD, 0x800F,                                                              CcFlags_o)
INST0(l_jno,            "jno",              IUM_RD, 0x810F,                                                              CcFlags_no)
INST0(l_jb,             "jb",               IUM_RD, 0x820F,                                                              CcFlags_b)
INST0(l_jae,            "jae",              IUM_RD, 0x830F,                                                              CcFlags_ae)
INST0(l_je,             "je",               IUM_RD, 0x840F,                                                              CcFlags_e)
INST0(l_jne,            "jne",              IUM_RD, 0x850F,                                                              CcFlags_ne)
INST0(l_jbe,            "jbe",              IUM_RD, 0x860F,                                                              CcFlags_be)
INST0(l_ja,             "ja",               IUM_RD, 0x870F,                                                              CcFlags_a)
INST0(l_js,             "js",               IUM_RD, 0x880F,                                                              CcFlags_s)
INST0(l_jns,            "jns",              IUM_RD, 0x890F,                                                              CcFlags_ns)
INST0(l_jp,             "jp",               IUM_RD, 0x8A0F,                                                              CcFlags_p)
INST0(l_jnp,            "jnp",              IUM_RD, 0x8B0F,                                                              CcFlags_np)
INST0(l_jl,             "jl",               IUM_RD, 0x8C0F,                                                              CcFlags_l)
INST0(l_jge,            "jge",              IUM_RD, 0x8D0F,                                                              CcFlags_ge)
INST0(l_jle,            "jle",              IUM_RD, 0x8E0F,                                                              CcFlags_le)
INST0(l_jg,             "jg",               IUM_RD, 0x8F0F,                                                              CcFlags_g)

INST0(align,            "align",            IUM_RD, BAD_CODE,                                                            None)
// clang-format on

#undef INST0
#undef INST1
#undef INST2
#undef INST3
#undef INST4
#undef INST5

#endif // TARGET_XARCH
